---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-gitops
  # labels:
  #   app: my-first-app
spec:
  replicas: 4
  selector:
    matchLabels:
      app: nginx-gitops
  template:
    metadata:
      labels:
        app: nginx-gitops
    spec:
      containers:
        - name: nginx
          image: nginx:1.23
          ports:
          - containerPort: 80
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
