---
apiVersion: v1
kind: Service
metadata:
  name: nginx-gitops
spec:
  selector:
    app: nginx-gitops
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30090
  type: NodePort
